services:
  app:
    image: node:lts-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3003:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: todos

  db:
    image: docker.io/library/mariadb:10.3
    volumes:
      - todo-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todos

volumes:
  todo-db: