services:
  app:
    image: todo
    ports:
      - 3003:3000
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: todos

  db:
    image: docker.io/library/mariadb:10.3
    volumes:
      - todo-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: todos

volumes:
  todo-db: